version: 1.0.{build}
image: Visual Studio 2017
build:
  verbosity: minimal
  project: FFXIVMonReborn.sln
clone_script:
- cmd: git clone --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%
- cmd: git checkout -qf %APPVEYOR_REPO_COMMIT%
- cmd: git submodule update --init
- cmd: nuget restore
